//vue入口配置项
//默认是vue有默认项，如果自己非要配置的话，新增vue.config.js去修改入口
module.exports={
    pages:{
        index:{
            entry:'src/main.js',
        },
    },
    //开启代理服务器
    devServer:{
        //这边配置代理的是你需要后端请求的服务器地址
        proxy:'http://localhost:8080/'
    }
}